package com.thedavelopers.eventqr.features.attendee

const val EXTRA_EVENT_ID = "extra_event_id"
const val EXTRA_EVENT_TITLE = "extra_event_title"
const val EXTRA_EVENT_LOCATION = "extra_event_location"
const val EXTRA_EVENT_DESCRIPTION = "extra_event_description"
const val EXTRA_EVENT_START = "extra_event_start"
const val EXTRA_EVENT_END = "extra_event_end"
const val EXTRA_EVENT_STATUS = "extra_event_status"
const val EXTRA_EVENT_CAPACITY = "extra_event_capacity"
const val EXTRA_EVENT_COUNT = "extra_event_count"
const val EXTRA_EVENT_CATEGORY = "extra_event_category"
const val EXTRA_PREFILL_EMAIL = "extra_prefill_email"
const val EXTRA_PREFILL_FULL_NAME = "extra_prefill_full_name"
const val EXTRA_REGISTRATION_ID = "extra_registration_id"
const val EXTRA_QR_CREDENTIAL_ID = "extra_qr_credential_id"
const val EXTRA_REWARD_ID = "extra_reward_id"
const val EXTRA_REWARD_NAME = "extra_reward_name"
const val EXTRA_REWARD_POINTS = "extra_reward_points"
const val EXTRA_REWARD_STOCK = "extra_reward_stock"
