package com.thedavelopers.eventqr.features.organizer

data class OrganizerMvpEvent(
    val id: String,
    val title: String,
    val organizerName: String,
    val dateTime: String,
    val shortDate: String,
    val venue: String,
    val status: String,
    val submittedDate: String,
    val adminRemarks: String,
    val additionalOrganizers: List<String>,
    val registeredCount: Int,
    val enteredCount: Int,
    val attendedCount: Int,
    val exitedCount: Int,
    val noShowCount: Int,
    val totalTransactions: Int,
    val successfulScans: Int,
    val rejectedScans: Int,
    val benefitClaims: Int,
    val boothSessionVisits: Int,
    val rewardRedemptions: Int,
    val totalPointsAwarded: Int,
    val idTemplateStatus: String,
    val rewardsStatus: String,
    val staffCount: Int,
    val scanPurposesCount: Int,
    val description: String = "",
    val registrationCloseDate: String = "-",
    val capacity: Int = 0,
    val currentAttendeeCount: Int = 0,
    val availableSlots: Int = 0,
)
