package com.thedavelopers.eventqr.features.staff

object StaffScreenExtras {
    const val EXTRA_EVENT_ID = "extra_event_id"
    const val EXTRA_EVENT_TITLE = "extra_event_title"
    const val EXTRA_SCAN_PURPOSE_ID = "extra_scan_purpose_id"
    const val EXTRA_SCAN_PURPOSE_NAME = "extra_scan_purpose_name"
    const val EXTRA_SCAN_PURPOSE_CODE = "extra_scan_purpose_code"
    const val EXTRA_QR_VALUE = "extra_qr_value"
    const val EXTRA_STAFF_USER_ID = "extra_staff_user_id"
    const val EXTRA_IS_VALID = "extra_is_valid"
    const val EXTRA_MESSAGE = "extra_message"
    const val EXTRA_ATTENDEE_ID = "extra_attendee_id"
    const val EXTRA_ATTENDEE_NAME = "extra_attendee_name"
    const val EXTRA_ATTENDEE_EMAIL = "extra_attendee_email"
    const val EXTRA_REGISTRATION_ID = "extra_registration_id"
    const val EXTRA_QR_CREDENTIAL_ID = "extra_qr_credential_id"
    const val EXTRA_REGISTRATION_STATUS = "extra_registration_status"
    const val EXTRA_VERIFIED_AT = "extra_verified_at"
    const val EXTRA_TRANSACTION_ID = "extra_transaction_id"
    const val EXTRA_TRANSACTION_RESULT = "extra_transaction_result"
    const val EXTRA_TRANSACTION_TYPE = "extra_transaction_type"
    const val EXTRA_POINTS_DELTA = "extra_points_delta"
    const val EXTRA_REASON = "extra_reason"
    const val EXTRA_SCANNED_AT = "extra_scanned_at"
    const val EXTRA_EVENT_TITLE_FALLBACK = "extra_event_title_fallback"
    const val EXTRA_ATTENDEE_EVENT_STATUS = "extra_attendee_event_status"
    const val EXTRA_QR_ACTIVE = "extra_qr_active"
}