package com.thedavelopers.eventqr.shared.constants;

public enum NotificationType {
    GENERAL,
    SCAN_APPROVED,
    SCAN_REJECTED,
    STAFF_ASSIGNMENT,
    REGISTRATION_NEW,
    CAPACITY_WARNING,
    CAPACITY_FULL,
    REWARD_EXHAUSTED,
    POINTS_ADJUSTED,
    EVENT_APPROVED,
    EVENT_REJECTED,
    EVENT_STARTING_SOON,
    EVENT_COMPLETED
}
